### ISSUE TITLE
I did not understand the instructions

### ISSUE THREAD

**Issue by Zkiva1** [scp222thj/MalumMenu#10]
I did not understand the instructions, I unziped the file and put the files that are inside the file into the among us file 
and it didn`t work, do I need to put it in to the Among Us_Data file?

**Comment by scp222thj** [comment]
You need to unzip this [ZIP](https://github.com/scp222thj/MalumMenu/releases/download/v1.1.2/MalumMenu-1.1.2.zip) and paste files in the "Among Us" folder. (If you do this correctly you should see a new folder called "BepInEx" next to "Among Us_Data")
