### ISSUE TITLE
Bugs and suggestions.

### ISSUE THREAD

**Issue by RobloxGabriel1** [scp222thj/MalumMenu#105]
When I get banned from lobbies, I can't join them and the features say no more annoying penalties. Can you fix it? Also, I would like to suggest a new feature where you can change somebody else's name and give other people roles.

**Comment by RobloxGabriel1** [comment]
Also make it so that you can have extra votes.

**Comment by jiggusuperking** [comment]
oh
he kicks me on lobby

**Comment by LilianPontes35** [comment]
_**I don't create, I just help answer**_

The annoying cheating penalties are not for banning rooms, but for other penalties.

Role and name switching can be done if you are the creator of the room equal to extra votes

**Comment by scp222thj** [comment]
> The annoying cheating penalties are not for banning rooms, but for other penalties.

Disconnect penalties specifically, which trigger when you disconnect too often from games and then the game stops you from joining any game for a specific amount of time

**Comment by Stellalyly** [comment]
Can it be added so that if the "see roles" isn't on, that the vote colors aren't different for crew and imp? because imp will show up in green when it says "so and so has voted" but crew will show up in white. can that be fixed?

**Comment by scp222thj** [comment]
@Stellalyly that has been fixed in the last update
