### ISSUE TITLE
Game doesn't start

### ISSUE THREAD

**Issue by FreshImmuc** [scp222thj/MalumMenu#107]
Installs but doesn't start after installation. Also deactivated windows defender realtime scan etc.

**Comment by RobloxGabriel1** [comment]
I think that if you want to install, you have to copy the files from the zip to the Among Us file. Then an installation will happen. You have to wait until it happens. (I'm not a developer or anything, I'm just a person that downloaded this.)

**Comment by jiggusuperking** [comment]
oh game game doesnt start?
easy way to fix this 
open game repeatedly until game launches
