### ISSUE TITLE
hey developer add new mod that named malum of us explaining in click here

### ISSUE THREAD

**Issue by jiggusuperking** [scp222thj/MalumMenu#111]
copy the mod from town of us and remove modded handshake pls developer 
and add public lobby support
town of us link
https://github.com/eDonnes124/Town-Of-Us-R
and remove in main manu that town of us
and add gamemodes that you want
if you dont know what gamemode you should add
go to this link
https://github.com/Rabek009/MoreGamemodes/

for unmodded players cannot used mods
i have idea 
[for imposters 
shapeshifting button as role
if imposter have 2 custom or more custom buttons 
add shapeshifting button as 2 or more
if imposter have 2 custom or more custom vent buttons
add  normal vent for players 
for crewmates 
if crew has 2 or more custom buttons
button as scientist button
if crew has 2 or more killing buttons
show all buttons as imposter note : other buttons sab or venting cannot be used
if crew has custom vent button
button as  engineer
for role showing in names
for custom gamemodes
for everyone as killer
everyone as imposter
for everyone as venting 
engineer as everyone]
that in bracket is for unmodded players using mods
add custom main menu pls do not in combine this is as separate dll file

**Comment by scp222thj** [comment]
I don't really see the point in starting this random side-project though? This is probably the most random request I have ever received on here lol.
