### ISSUE TITLE
hey shapeshifter works in this mod

### ISSUE THREAD

**Issue by jiggusuperking** [scp222thj/MalumMenu#112]
when i am joining lobby as classic
also changing role in lobby but it shows shapeshifter
after game started
i see shapeshifting tab buut it looks everyone named wwwwwwwwwwwwwwwww

**Comment by LilianPontes35** [comment]
This is due to the fact that if you try to turn into wwwwwwww..., you will be kicked out of the room, even if you are the creator. This is because of AntiCheat in Among Us
