### ISSUE TITLE
DELETE BUTTON NOT WORKING TO OPEN MOD MENU

### ISSUE THREAD

**Issue by Roebuck01** [scp222thj/MalumMenu#114]
When I go onto the game, the mod menu doesn't pop up as delete. So I dont know if you've changed it.

Your last update it worked but now no.
![Capture](https://github.com/scp222thj/MalumMenu/assets/173207943/d1a21e5f-bba0-4424-82ce-f8bafdf31afc)

**Comment by RobloxGabriel1** [comment]
2 ways: the creator changed the hotkey. another way is that among us patched it so when you press del, nothing happens. thats because of the new update.

**Comment by LilianPontes35** [comment]
o mod ainda não tem suporta a versao que vc joga

**Comment by Roebuck01** [comment]
Hello, is there any update to when the mod menu will be done?

**Comment by astra1dev** [comment]
If you joined the discord server, you would know that the update is going to release today or tomorrow.

**Comment by scp222thj** [comment]
The latest update is out right now!
