### ISSUE TITLE
I cannot open the menu

### ISSUE THREAD

**Issue by MedIs-Glitch** [scp222thj/MalumMenu#117]
I have the last among us update (from epic games) and the last mod update (downloaded it after 6 hours from the last commit) I also disabled windows defender but sadly it's not working as in the photo.

![amongus](https://github.com/scp222thj/MalumMenu/assets/139562902/90bddb90-68c3-46c3-8256-011642063d62)

**Comment by scp222thj** [comment]
the new version is coming out by the end of the week, I announced it in the official Discord server.
