### ISSUE TITLE
Please Please Add This Suggestion 😢

### ISSUE THREAD

**Issue by Cole775** [scp222thj/MalumMenu#125]
Please can you add a cheat in the menu that can increase the player's level and OTHER people's player?

Like for example, I can choose someone in the lobby to increase their level. Please, please, make it happen. I'm begging 🙏

**Comment by astra1dev** [comment]
Would be a cool feature, thanks for the suggestion.
Unfortunately, there is no way to modify the level of a player as it is stored on the server.

**Comment by scp222thj** [comment]
@astra1dev I guess maybe you could change their levels locally as a host, idk if they meant that.

**Comment by scp222thj** [comment]
@LilianPontes35 yea i worded it wrong. I meant the host can change other people's levels in a game but when they leave it will reset to the normal value and nothing will have changed ofc.
