### ISSUE TITLE
Please add this. #amongus @scp222thj #malumMenu read desc

### ISSUE THREAD

**Issue by mogus2124** [scp222thj/MalumMenu#128]
Hello ive been loving your menu for among us. There is a section called set role. You can change to the classic imposter and all the crewmates. My question is... can you add the ability to choose phantom or shapeshifter? i think itd make a great additon to the menu.

**Comment by GimNerd22** [comment]
I think the anticheat will kick you if you do that

**Comment by 1BenPro** [comment]
In my opinion, they should add noclip for other players and some options for the hide and seek game mode.

**Comment by mogus2124** [comment]
Oh ok thx for respondSent from my iPhoneOn Jun 27, 2024, at 12:57 PM, 1BenPro ***@***.***> wrote:﻿
In my opinion, they should add noclip for other players and some options for the hide and seek game mode.
