### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by cxrzaza** [scp222thj/MalumMenu#135]
So i download it and when i start it it says offline

**Comment by astra1dev** [comment]
Hi there! Could you please repeat your question and provide a bit more detail about the problem you're facing? This will help me understand better and assist you more effectively. Thank you!

**Comment by Sand-and-Beans** [comment]
> So i download it and when i start it it says offline

I guess you need to add this
[steam_appid.txt](https://github.com/user-attachments/files/16234727/steam_appid.txt)
to your file

**Comment by cxrzaza** [comment]
so i open the game and i play then they say like im offline and i'm getting
something like a warnet and i cant play online so yeah sorry for late
respond

‫في الخميس، 4 يوليو 2024 في 9:20 م تمت كتابة ما يلي بواسطة ‪Astral✨‬‏ <‪
***@***.***‬‏>:‬

**Comment by scp222thj** [comment]
You can try enabling guest mode in the config file settings, it might fix this issue.

**Comment by cxrzaza** [comment]
so am i baned or not i didn't understand

في أحد، 21 تموز، 2024 في 8:15 م، كتب Scp222ThJ ***@***.***>:

**Comment by scp222thj** [comment]
Nope, it's just an issue that only some people face for some reason
