### ISSUE TITLE
this isnt really a issue but if you can "can" you add anti ban

### ISSUE THREAD

**Issue by Ethangamer121** [scp222thj/MalumMenu#138]
anti ban is where the host and other people cant ban you or kick you please if you can add this in like passive selction

**Comment by LilianPontes35** [comment]
Impossible because this ban is server-side. please close this problem

**Comment by scp222thj** [comment]
Yeah, it's impossible. The only thing you can do is bypass a ban and join back the lobby by using a proxy or VPN to change your IP.
