### ISSUE TITLE
It just doesn't work for me.

### ISSUE THREAD

**Issue by TheBlitzBlader** [scp222thj/MalumMenu#14]
Hi I was wondering if you could please help me with getting your mod to work I followed all the steps and it just doesn't work. I really really want this to work though. Not a lot of things work out for me and I don't want this one to be just another one of them. If you could help me I'd really appreciate it! Thank You.

**Comment by kk-dev7** [comment]
You need to unzip this [ZIP](https://github.com/scp222thj/MalumMenu/releases/download/v1.1.2/MalumMenu-1.1.2.zip) and paste its files in the "Among Us" folder. The Among Us folder is where "AmongUs.exe" is located. (If you do this correctly you should see a new folder called "BepInEx" next to "Among Us_Data")

**Comment by TheBlitzBlader** [comment]
> You need to unzip this [ZIP](https://github.com/scp222thj/MalumMenu/releases/download/v1.1.2/MalumMenu-1.1.2.zip) and paste its files in the "Among Us" folder. The Among Us folder is where "AmongUs.exe" is located. (If you do this correctly you should see a new folder called "BepInEx" next to "Among Us_Data")

**Comment by TheBlitzBlader** [comment]
Yes that's what i'm saying nothing happens when I do this.

**Comment by TheBlitzBlader** [comment]
Sorry I don't know if you got my reply but what I'm saying is I followed that instruction and it still doesn't work

**Comment by scp222thj** [comment]
Can you see the mod icon on the top right of your game screen? @TheBlitzBlader

**Comment by TheBlitzBlader** [comment]
@scp222thj No I can't

**Comment by scp222thj** [comment]
@TheBlitzBlader Completely reinstall (uninstall and install again) Among Us and install the mod again using the instructions. Then run the game and make sure to **wait** because it might take a while to run the first time. Then, check if you still can't see the mod icon on the upper-right side of the game window

**Comment by TheBlitzBlader** [comment]
@scp222thj ok I uninstalled and reinstalled it again but I have a question do I just paste it on this screen or do I go inside the among us data folder and paste it?
![Screenshot (12)](https://github.com/scp222thj/MalumMenu/assets/144578791/f64e23da-1e9b-436f-b9e6-5a26dbd2c1e4)

/

**Comment by scp222thj** [comment]
@TheBlitzBlader Paste the contents of the ZIP in the folder you are right now (remember to paste only the contents of the ZIP, not the ZIP file itself)

**Comment by TheBlitzBlader** [comment]
@scp222thj THANK YOU SO MUCH IT WORKED AFTER I DID THAT. IT WAS SO FUN TOO! Seriously thanks for helping me man I really appreciate it.
