### ISSUE TITLE
Can't load into game

### ISSUE THREAD

**Issue by AxolotlBuddy1** [scp222thj/MalumMenu#142]
Hello, im filing a report here due of a loop in my game, the game is continuously loading in the running green little among us thing.
Sadly i cannot fix this and its seems in BepInEx is like with TextDataProvider, Runtimedata is null, Unable to load runtime data, InvalidKeyException thrown, Chainoperation Failed, NullReferenceException: Object reference not set to an instance of an object.
[EDIT: If you need extra information please ask in the comments, thanks.]
I don't know how or why this happend. Can i get some assistance please?

Thank you.

**Comment by scp222thj** [comment]
You are using the latest versions of AU and the mod, right?

**Comment by AxolotlBuddy1** [comment]
Yes im using the right mod version with the mod installed correctly and the version is compatible with among us.

**Comment by scp222thj** [comment]
I think you should just join the [Discord server](https://discord.gg/YYcYf88jAb) and get support there, it's much easier!
