### ISSUE TITLE
You get kicked out of game when you change fake role to Phanton and try to vanish

### ISSUE THREAD

**Issue by ai-prompting** [scp222thj/MalumMenu#146]
You get kicked out of game when you change fake role to Phanton and try to vanish. Also you are then banned from that lobby.

**Comment by astra1dev** [comment]
hmm seems like anticheat got updated or something

**Comment by scp222thj** [comment]
You shouldn't be able to change fake role to phantom normally, it seems you might have encountered a bug of some kind. I'm pretty sure I fixed it in the upcoming update though, I just didn't commit the code yet.
