### ISSUE TITLE
[Suggestion] Add

### ISSUE THREAD

**Issue by Night-GUA** [scp222thj/MalumMenu#151]
- null chat note
- private chat 
- chat as another player

**Comment by scp222thj** [comment]
I think most of these are detected by anticheat except the private chat, which can be easily detected by mod anticheats. So I don't think I'll be able to add any of these any time soon 🤷.

**Comment by Night-GUA** [comment]
oh so cool

**Comment by Night-GUA** [comment]
AUM Chat sent their rpc to be detected
