### ISSUE TITLE
não estou conseguindo abrir o painel do Hacker

### ISSUE THREAD

**Issue by gamitox** [scp222thj/MalumMenu#152]
eu baixei o mod e estalei de acordo com que estava escrito mas só aparece a figura com nome MOD quando aperto no botão direito não aparece o painel 
![image](https://github.com/user-attachments/assets/0e32731a-cdbc-4186-8516-db7bcef7e825)
![Imagem do WhatsApp de 2024-08-08 à(s) 11 16 47_aa39ca80](https://github.com/user-attachments/assets/cf5911f7-78ef-4eb6-9c29-c49e710ea04b)

**Comment by Pietrodjaowjao** [comment]
Não é o botão direito, é a tecla "DEL" ou "DELETE"
