### ISSUE TITLE
Update the Mod Cheat

### ISSUE THREAD

**Issue by AlexYT-droid** [scp222thj/MalumMenu#158]
Hi Scp222thj.

according to innersloth, Among Us has been Updated to v2024.8.13 because there is new cosmicube

and your mod cheat is not least now...

i want you to put your mod in least among us version v2024.8.13 please

**Comment by astra1dev** [comment]
Quote from discord announcement scp posted a few hours ago:

``` 
I predict the MM update compatible with the latest AU version will be ready and posted on Saturday. I just need to fix some small bugs caused by the update, but luckily nothing major was broken. I can't give a specific time though.

Please remember that this is not set in stone and might change depending on how busy I end up being, but I'll do my best to get it out by then
```
also remember this is a free product and we are **not** obligated to update it every time in matter of seconds when a new AU update drops.

**Comment by AlexYT-droid** [comment]
wait so there is no more updates from this mod cheat

For: astra1dev

**Comment by astra1dev** [comment]
You didnt read the quote my friend otherwise you would know new update is planned for saturday
