### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by CDsausage** [scp222thj/MalumMenu#159]
Can you add a feature where you can insert a name and  can apply it a player or anyone in the lobby to have the same name as you applied.
Want to have the same name for my friend when we are playing like the III username trick from back then.
Would be very cool, Thanks!

**Comment by GimNerd22** [comment]
probably wouldn't work unless host, anticheat could be a problem

**Comment by SCP294-1** [comment]
If you are the host it will work

**Comment by scp222thj** [comment]
Yea this could work as a host-only cheat
