### ISSUE TITLE
the functions in the host menu doesn't work as intended

### ISSUE THREAD

**Issue by luciferblood427** [scp222thj/MalumMenu#172]
so i tried to host a match and use it the mods but they don't seem to work at all. when i started the game to test them, i clicked every single one but to no avail, any suggestions on how to get them to work?

**Comment by Amirreza-Sal86** [comment]
I have the same problem
If anyone knows what the problem is, please help

**Comment by scp222thj** [comment]
This is a known bug. I will release a new update in the weekend to hopefully fix this.
