### ISSUE TITLE
Killing buttons are not working.

### ISSUE THREAD

**Issue by michaelfawcett1** [scp222thj/MalumMenu#173]
https://github.com/user-attachments/assets/6cb5592d-9f14-4350-ade1-fc758494d4a6

I tried to kill players by creating my room, but it didn't work.

**Comment by scp222thj** [comment]
This is a known bug. I will release a new update in the weekend to hopefully fix this.

**Comment by Amirreza-Sal86** [comment]
Thanks a lot❤👌💪

**Comment by michaelfawcett1** [comment]
Thanks Bro.
