### ISSUE TITLE
Please add "Guardian Angel" role in Among Us Cheat

### ISSUE THREAD

**Issue by Amirreza-Sal86** [scp222thj/MalumMenu#174]
Hi
thanks a lot for you incredible(!) cheat for Among Us
Please add "Guardian Angel" role in "Set Fake Roles" section.
and add "No Protect Cooldown" option.
I know in the latest version of among us, a few cheat options are in trouble (like "Kill Player" in "Murder" section) and I can't use them in "Host-Only" section recently; but if you can get these problems out of the way and return these options, It will be Great!
Thanks a lot!

**Comment by michaelfawcett1** [comment]
yeah we want this feature.

**Comment by Ethangamer121** [comment]
there was but they removed the most fun parts like being a imposter or killing people

**Comment by astra1dev** [comment]
I'm not sure but this could be impossible because of anticheat

**Comment by scp222thj** [comment]
Guardian Angel cheats are closely guarded by the anticheat for some reason, so I doubt this can be a thing. But I'll see.
