### ISSUE TITLE
Game keeps crashing

### ISSUE THREAD

**Issue by Jammos1** [scp222thj/MalumMenu#181]
Whenever i kill someone when im imposter the game just crashes, and sometimes when i do a task the game crashes and sometimes even if i enable a mod on the menu, so for example i could activate show roles and my game just crashes.

**Comment by scp222thj** [comment]
Honestly, it seems like maybe your machine has some performance issues that make it so the mod can't run? It's the only reason I could think of, because no one else seems to be experiencing this to such extent.
