### ISSUE TITLE
Stopped working after re-instalation, but I did everything the same

### ISSUE THREAD

**Issue by do0mfan** [scp222thj/MalumMenu#183]
It worked really well before, but I had to reinstall it a few times when it did not connect to my Steam account.

Today, when the same thing happened, I tried to reinstall it. When it finally installed, it did not work, and I did everything the same as before.

I copied the Among Us files to a separate folder and inserted the Menu's files into it. (It normally also shows a popup asking if I want to replace the files; this time, it did not happen.)

Among Us launched without the console, and the Menu did not work, as if it was never installed.

I tried reinstalling both the Menu and the game itself, but still nothing.

Has anyone else experienced this?

**Comment by Ethangamer121** [comment]
no but i think i know how fix put all files in among us steam folder with copying any files

**Comment by astra1dev** [comment]
Are you sure you are downloading the correct zip file? Microsoft Store version has been added lately so theres 2 different zips you can download. Also try verifying the file integrity via Steam.

**Comment by do0mfan** [comment]
> no but i think i know how fix put all files in among us steam folder with copying any files

I tried this already, didn’t work:(

**Comment by do0mfan** [comment]
> Are you sure you are downloading the correct zip file? Microsoft Store version has been added lately so theres 2 different zips you can download. Also try verifying the file integrity via Steam.

Wait Yeah, you may be right, I am using the wrong version probably
