### ISSUE TITLE
Idea :D

### ISSUE THREAD

**Issue by JaimeJams** [scp222thj/MalumMenu#184]
So, for my idea, maybe make a mod to like create a bot so it can do the task for you, and if its imposter it will kill everyone quick, and if the noise maker gets killed, it wont make a sound. Also for the bot can you customize it in like a button menu? That would be great, and also (again) can you make a new GUI for the menu, and add like a custom button to open the menu, and yeah. That's all for me.

**Comment by scp222thj** [comment]
1. Botting isn't really easy to implement, and also I don't have plans for it. Also, we already have a Complete All Tasks cheat?
2. Noisemaker is handled client-side so this isn't possible.
3. Plans for a new GUI are being made yea.
4. Custom shortcut to open the menu is already a thing, you just need to use the config file.
