### ISSUE TITLE
Menu not opening when Pressing DELETE

### ISSUE THREAD

**Issue by ytThatTree** [scp222thj/MalumMenu#20]
Me and my friend downloaded it and the menu also started with the game (We see the tag and got the news ingame at the bottom left). But when we press DELETE nothing happens and the promised window does not open. We have tried every possible keybind out of panic but nothing works. My arms start shaking and my head vibrates.

**Comment by kylian-duval** [comment]
it stopped working after the last update

**Comment by kylian-duval** [comment]
worked great yesterday

**Comment by kylian-duval** [comment]
please fix the problem

**Comment by scp222thj** [comment]
Yeah it's probably because I didn't update the code. I'm in vacation rn but I will update as soon as I'm back.

**Comment by kylian-duval** [comment]
Okay, no worries, I don't think it's a big deal because the option to unlock all the cosmetics works just fine.

**Comment by HeckerCatYT** [comment]
> Okay, no worries, I don't think it's a big deal because the option to unlock all the cosmetics works just fine.

the entire thing dosent work besides the update area.

**Comment by Lukim99** [comment]
MainUI and vent features are not working
other features seem to be working properly
simply update the AmongUs.GameLibs.Steam package to the latest version

**Comment by Lukim99** [comment]
> I think I've managed to update AmongUs.GameLibs.Steam but I don't know how to build the project and then install it in game.

After updating the package, make general modifications to your code to accommodate the new methods.
Afterwards, if the build is completed successfully, copy src/bin/Release/net6.0/MalumMenu.dll and paste it into BepInEx/plugins.

**Comment by kylian-duval** [comment]
Since I did the update it compiles more. It can no longer find the "RpcShapeshift" method in the PlayerControl class.

**Comment by Lukim99** [comment]
> Since I did the update it compiles more. It can no longer find the "RpcShapeshift" method in the PlayerControl class.

Find a new method that corresponds to it. You can find it by typing Rpc in Visual Studio and looking at the autocomplete list.

**Comment by kylian-duval** [comment]
I agree, but I'm thinking of stopping now. I'd rather leave it up to the creator of the project. @scp222thj

**Comment by scp222thj** [comment]
Guys, good news! I've come back from my vacation and am currently working on updating everything. I've already updated all the old methods and classes with the new corresponding ones, and now I'm working on fixing some issues caused by the recent changes to the game, such as the new map. Hopefully, I'll be done in a couple of days, and then the menu should work just fine!

**Comment by scp222thj** [comment]
Guys, good news! I've come back from my vacation and am currently working on updating everything. I've already updated all the old methods and classes with the new corresponding ones, and now I'm working on fixing some issues caused by the recent changes to the game, such as the new map. Hopefully, I'll be done in a couple of days, and then the menu should work just fine!

(Btw thanks to @kk-dev7 for helping with the issues while I was gone)

**Comment by kylian-duval** [comment]
Sorry I tried to answer the problems but I could not understand the code 😂

**Comment by scp222thj** [comment]
@kylian-duval I think I'm going to write a better guide for contributing to this project with all the resources I use when developing the mod, so hopefully more people can understand and work with my code

**Comment by kylian-duval** [comment]
@scp222thj thank you very much

**Comment by kylian-duval** [comment]
thank you @kk-dev7

**Comment by kylian-duval** [comment]
@scp222thj You can fix anything ?

**Comment by Aware-ok** [comment]
Any update?

**Comment by kylian-duval** [comment]
@Aware-ok no 😭

**Comment by astra1dev** [comment]
@scp222thj not to be annoying or anything, but it's been 3 weeks... are you still working on it? if no i would consider forking mm and updating it to be compatible with the newest version

**Comment by Aware-ok** [comment]
I guess he is taking another vacation

**Comment by scp222thj** [comment]
I wish I was taking another vacation 💀. I have been so damn busy and I didn't have time to update the code, but now I finally did it! You can install the new version [here](https://github.com/scp222thj/MalumMenu/releases/tag/v1.2.0). Thanks to all the people who responded to issues and helped while I was gone. I'm sorry for how long it took 🥲

**Comment by ayman1623** [comment]
yes

**Comment by Lukim99** [comment]
> I wish I was taking another vacation 💀. I have been so damn busy and I didn't have time to update the code, but now I finally did it! You can install the new version [here](https://github.com/scp222thj/MalumMenu/releases/tag/v1.2.0). Thanks to all the people who responded to issues and helped while I was gone. I'm sorry for how long it took 🥲
> 
> By the way, should I make a Discord server for this mod? I feel like it would be a lot easier to talk to you guys that way...

Let's make a Discord! It would be better to develop more and more powerful functions through quick communication. The potential of this menu is beyond imagination.

**Comment by kylian-duval** [comment]
yes @scp222thj a discord

**Comment by astra1dev** [comment]
tbh i was about to fork and update MM haha :) 
btw a discord would be wonderful ✨

**Comment by Aware-ok** [comment]
i agree

**Comment by scp222thj** [comment]
I just finished setting up the Discord! Here it is: [discord.gg/YYcYf88jAb](https://discord.gg/YYcYf88jAb)
