### ISSUE TITLE
Microsoft version kinda buggy

### ISSUE THREAD

**Issue by SomeRandomFella** [scp222thj/MalumMenu#209]
So everytime I open up the micorosft version it says the version of among us and malum menu are incompatible and yes i have the latest version also the kill one doesn't work even as host

**Comment by astra1dev** [comment]
Everything you mentioned has been said before in earlier issues. Please close this one, thank you.

**Comment by SomeRandomFella** [comment]
and none of them have been answered

**Comment by astra1dev** [comment]
The versions aren't incompatible. Version 2.4.2 is the latest one. Kill not working is a known issue and will be fixed.

**Comment by SomeRandomFella** [comment]
Thank you.
