### ISSUE TITLE
unable to open menu

### ISSUE THREAD

**Issue by imnathy** [scp222thj/MalumMenu#22]
managed to get everything working, but im unable to open the menus, so im not sure how to do that. read the instructions that said use delete key, have pressed every key on my keyboard, so im not sure what to do

**Comment by kylian-duval** [comment]
It doesn't work anymore since the last update of among us. The developer has to update his code.

**Comment by scp222thj** [comment]
The update is out now! Sorry for the delay! Install the latest [version](https://github.com/scp222thj/MalumMenu/releases/tag/v1.2.0) and your issue is likely fixed!
