### ISSUE TITLE
Menu won't open

### ISSUE THREAD

**Issue by ThePandaPenguin** [scp222thj/MalumMenu#25]
I've extracted the contents of the zip file into the steam folder as the guide said. (See image). The game took a lot longer to launch and to join a game actually which was also mentioned in the guide. This made me think it was gonna work. Once the game loaded up, I got the news panel titled "Malum Menu" giving instructions telling me to open the mod menu with the Delete key - but now that I'm in a game, pressing delete does nothing..? Not sure if I've done something wrong but some guidance would be appreciated loads.
![Screenshot 2023-11-02 221902](https://github.com/scp222thj/MalumMenu/assets/34004179/57d4e415-5679-433c-aba2-48787ffc31a0)

**Comment by ThePandaPenguin** [comment]
just realised many people have the same issue so ignore this

**Comment by kk-dev7** [comment]
https://github.com/scp222thj/MalumMenu/issues/20
also scp said hes on vacation and will fix it soon
