### ISSUE TITLE
[BUG]  - Cannot join a game

### ISSUE THREAD

**Issue by AmibeSkyfy16** [scp222thj/MalumMenu#3]
There is a bug saying: Incorrect chat mode: This room was made for Quick Chat Only. Your setting is Free Chat.

But my setting is Quick Chat Only !

I try to switch to Quick Chat, but it puts me back in Free Chat and I can't do anything.
Having uninstalled the mod, the problem was solved. 

However, the first time I used the mod, I didn't have this problem.

**Comment by scp222thj** [comment]
Yep, it was a problem with the UnlockFeatures cheat. Fixed it in latest release: [v1.1.2](https://github.com/scp222thj/MalumMenu/releases/v1.1.2)
