### ISSUE TITLE
Hotkey Not Working

### ISSUE THREAD

**Issue by Hiverpool** [scp222thj/MalumMenu#36]
When im inside a game, i cannot open the cheat menu, even though im pressing the delete button, i have tried to close and open among us again, however it still doesn't work

**Comment by Kopp56-PRO** [comment]
Not working on latest update. Update soon

**Comment by scp222thj** [comment]
Latest [update](https://github.com/scp222thj/MalumMenu/releases/tag/v1.2.0) just came out! Install it now and it should fix your issue
