### ISSUE TITLE
dont work de;

### ISSUE THREAD

**Issue by Kartex99** [scp222thj/MalumMenu#37]

**Comment by Paraplayz** [comment]
i personally have to problem that the game doesn't appear to register the mod or something and so it doesn't activate

**Comment by scp222thj** [comment]
1 Are you absolutely sure you are using the latest version of the mod?
2 What platform are you using to run Among Us (e.g Steam, Itch.io, Epic)? 
3 Could you send a full screenshot of your "Among Us" folder after installation?

**Comment by Paraplayz** [comment]
@scp222thj 1. yes 2. Steam 3:
![Screenshot (3073)](https://github.com/scp222thj/MalumMenu/assets/119504618/eb5c7edb-9ae0-4c85-b244-3d8e8ead2ced)

**Comment by scp222thj** [comment]
@Paraplayz okay I think I see the problem! Go into the folder named "BepInEx" and then go into "plugins". Paste the MalumMenu DLL file (not the ZIP!) into this "plugins" folder.

**Comment by Paraplayz** [comment]
that fixed it, thanks!
