### ISSUE TITLE
PlayerControl.RpcRevertShapeshift doesnt exist in v2023.11.28

### ISSUE THREAD

**Issue by BananaDude508** [scp222thj/MalumMenu#39]
I recompiled the mod to the newest among us version (v2023.11.28), however the mod doesnt open the menu unless the codeblock relating to `PlayerControl.RpcRevertShapeshift` in NoCooldownPatched.cs. After commenting out the codeblock the mod compiles and launches perfectly fine, except the shapeshift nocooldown doesnt work. `PlayerControl.RpcShapeshift` codeblock does not need to be commented.
In newest version i _think_ that disabling cooldowns does nothing and needs to be updated, other mod still functions as intended in my experience.

Before asked no i have not created an updated repo/fork of malummenu and i dont intend to as you really only need to change 1 line of code, comment out a block and then recompile.

**Comment by Lukim99** [comment]
Instead of commenting out `PlayerControl.RpcRevertShapeshift`, change it to `PlayerControl.RpcRejectShapeshift`. Its method name has been changed.

**Comment by susmicrosoftagentboi** [comment]
how do i compile the c# project for the new among us version?

**Comment by Kopp56-PRO** [comment]
Please add an updated fork/repo or just send it to me, i just want to use it

**Comment by susmicrosoftagentboi** [comment]
how? i get an error when i change  `PlayerControl.RpcRevertShapeshift` to `PlayerControl.RpcRejectShapeshift`, and i get an error when i comment out the code. either way, it compiles fine but crashes the game on launch. and i did change the version number in `MalumMenuPlugin.cs` and `MalumMenu.csproj`

**Comment by ayman1623** [comment]
so can someone give me a step by step to do this

**Comment by Lukim99** [comment]
> so can someone give me a step by step to do this

1. Download this git
2. Open with Visual Studio 2022
3. Update `AmongUs.GameLibs.Steam` to the latest version in Dependencies -> Packages.
4. Change all error-producing methods to the latest methods.
5. Change the configuration to `Release` and build the solution.
6. Copy `MalumMenu.dll` located in `MalumMenu-main\src\bin\Debug\net6.0` and paste it into `BepInEx\plugins`.


I have explained it step by step for you. If you're an idiot who doesn't even understand this, I'm not willing to answer any further.

**Comment by BananaDude508** [comment]
> Instead of commenting out `PlayerControl.RpcRevertShapeshift`, change it to `PlayerControl.RpcRejectShapeshift`. Its method name has been changed.

I can't find a definition for `PlayerControl.RpcRejectShapeshift`.
I have tried building after changing the called methods into reject, even removing bool like you said however compile fails. Error claims there is no definition for `PlayerControl.RpcRejectShapeshift`, and after reviewing `PlayerControl.cs` there is no definition for `RpcRejectShapeshift`

I will be uploading a fork of the git with the updated version until this version is maintained to the newest among us version

https://github.com/BananaDude508/MalumMenu

**Comment by BananaDude508** [comment]
So my fork is now redundant, i may add my own features so i wont make it inactive. also i figure out why is wasnt compiling, i updated `AmongUs.GameLibs.Steam` but i _didnt_ update it in the code :facepalm:

**Comment by ayman1623** [comment]
dont understand any of this coding stuff, can someone just tell me how to update the menu so i can use this

**Comment by scp222thj** [comment]
I have updated the mod with all the latest assemblies and bugfixes! You can install it [here](https://github.com/scp222thj/MalumMenu/releases/tag/v1.2.0)
