### ISSUE TITLE
[BUG] with stairs on airship

### ISSUE THREAD

**Issue by AmibeSkyfy16** [scp222thj/MalumMenu#4]
enabling NoClip when going on the stairs solved the problem, but ortherwise you are stuck on the stairs with an infinite animation

**Comment by scp222thj** [comment]
That was a weird ass bug! I guess I never noticed because I don't play AirShip as much. Fixed in latest release: [v1.1.2](https://github.com/scp222thj/MalumMenu/releases/v1.1.2)
