### ISSUE TITLE
Yeah

### ISSUE THREAD

**Issue by Inspector-of-artotska** [scp222thj/MalumMenu#41]
When i open  the game it just closes

**Comment by Lukim99** [comment]
Open again or update your game

**Comment by Inspector-of-artotska** [comment]
Found the error, it was on reisntalling by 0 the files of steam

**Comment by scp222thj** [comment]
@Inspector-of-artotska so the mod works fine now?

**Comment by Inspector-of-artotska** [comment]
Yup, it does 100% work, you just have to uninstall and install before injecting it to your gamefiles, or atleast it how it worked for me
