### ISSUE TITLE
game crashes randomly

### ISSUE THREAD

**Issue by gamestartergame** [scp222thj/MalumMenu#43]
after playing the game for a while it randomly crashes

**Comment by Lukim99** [comment]
what features did you turn on?

**Comment by gamestartergame** [comment]
had esp , venting , traces , mini map that shows imposters , noclip , turned speed hack on but turned that off

**Comment by scp222thj** [comment]
Could you try to replicate the crash? Maybe it was a one-off event...

**Comment by astra1dev** [comment]
are you still there @gamestartergame ?
