### ISSUE TITLE
How to unistall ?

### ISSUE THREAD

**Issue by dpery** [scp222thj/MalumMenu#83]
> how can i unistall it ? and how can i disable free cosmetics and other passive cheat cause it wont turn off

**Comment by astra1dev** [comment]
Hi!
If you want to uninstall MalumMenu, delete the file `MalumMenu.dll` inside the folder `[PATH_TO_YOUR_AMONGUS_GAME/BepInEx/plugins` 

You can't turn off passive cheats.

Have a nice day!
