### ISSUE TITLE
BepInEx not loading in the game

### ISSUE THREAD

**Issue by plyrnoob2890** [scp222thj/MalumMenu#86]
i have it installed with malum menu
it doesn't do anything, it only opens among us and nothing else

**Comment by astra1dev** [comment]
Can you explain your issue a little more? 
Can you see the mod icon on the top right of your screen?

**Comment by plyrnoob2890** [comment]
> Can you explain your issue a little more? Can you see the mod icon on the top right of your screen?

I have everything installed, but when I open Among Us it just doesn't show up the mod icon

**Comment by astra1dev** [comment]
Do you see the BepInEx console pop up?

by the way, you can send a screenshot of your among us folder so i can check if you installed MM correctly

**Comment by scp222thj** [comment]
@plyrnoob2890 are you there?

**Comment by StonedRacer42** [comment]
Im having the same issue now. When I launch among us with the mod menu, the game loads up but I cant open the menu and this is what the console says.
![ScreenShot_6_18_2024_4_26_55_PM](https://github.com/scp222thj/MalumMenu/assets/173201650/a09dd9d8-1d01-4fc9-88ff-02a2e5a5c538)
![ScreenShot_6_18_2024_4_26_32_PM](https://github.com/scp222thj/MalumMenu/assets/173201650/663d16c4-b95a-4758-8c78-0711bec534cf)
![ScreenShot_6_18_2024_4_26_48_PM](https://github.com/scp222thj/MalumMenu/assets/173201650/5d5de540-f91f-49e9-a013-fa8a979b963b)

**Comment by scp222thj** [comment]
This is probably because Among Us just received a massive update that broke all mod menus out there. I'm working on a new compatible version which will hopefully be released by the end of the week.

**Comment by StonedRacer42** [comment]
oh ok bet, is there a way to be notified whenever its released?

**Comment by scp222thj** [comment]
@StonedRacer42 I always announce it on Discord when a new version is out
