### ISSUE TITLE
Can't login when you don't have a friendcode.

### ISSUE THREAD

**Issue by GUI233** [scp222thj/MalumMenu#87]
"Couldnt connect to your Among Us Account.
(Error FriendCodeFail)"

The underage mode can hide your friendcode, and you can't login without friendcode when loading the menu.

And can you hack a fake friendcode to escape the ban list?

**Comment by scp222thj** [comment]
This error usually happens when you start the game using its exe file instead of a launcher (Steam, Epic Games, etc.). You need to start it from the launcher for it to work.

**Comment by GUI233** [comment]
No I meant if you hide the friendcode to escape the banlist,this will happen and couldn't be solved by starting from the launcher.
![VI$(F0BVTDX7QRQ`3V$47NX](https://github.com/scp222thj/MalumMenu/assets/141896954/75f0310b-5cda-4763-ae82-0ac0acf82f17)
![5I07} `($LQVMOME{K9N8N0](https://github.com/scp222thj/MalumMenu/assets/141896954/58b4f5b2-d8bd-41d6-be42-547bee2e12e1)
![ZVZRSSX7TI7R@8CHY 51 VM](https://github.com/scp222thj/MalumMenu/assets/141896954/57bb4834-d13e-4c3b-ad11-5bf3edb60190)

**Comment by GUI233** [comment]
with the empty friendcode
![VI$(F0BVTDX7QRQ`3V$47NX](https://github.com/scp222thj/MalumMenu/assets/141896954/a6223739-ea06-48b2-958c-60dafd1067bb)

**Comment by GUI233** [comment]
Oh...wait...what a perfect GuestMode, there's no need to use Among Us's own way to hide  friendcode!Praise the MalunMenu lol

**Comment by scp222thj** [comment]
@GUI233 so is it fixed lol?

**Comment by GUI233** [comment]
> @GUI233 so is it fixed lol?

No.If you don't have a FriendCode,MM doesn't work. But your GuestMode is completely superior to my method.It can escape banlist as well!

**Comment by scp222thj** [comment]
good good!
