### ISSUE TITLE
Cant connect to online games not even my own

### ISSUE THREAD

**Issue by MRGbrick** [scp222thj/MalumMenu#89]
Im having issues connecting to online games. it started off not working so i reset my game. after i did that it worked for 3 games then would not let me connect again and still doesnt work it says "you disconnected from server reliable packet 0 (size=44) was not ack'd
after 7809ms (9 resends) pls help the menus awesome btw works great and all just that one issue.

**Comment by scp222thj** [comment]
Try connecting to an online game without the menu installed, the problem might be unrelated to the mod.

**Comment by MRGbrick** [comment]
amazing debug work it totally works now.... still does not explain not being able to join my own games but okay. im just gonna make my own menu that actually works lol

**Comment by scp222thj** [comment]
Are you using some other mods or a cracked version?
