### ISSUE TITLE
Idk

### ISSUE THREAD

**Issue by Dmitriy224** [scp222thj/MalumMenu#94]
I noticed that when you change your role to a traitor during the game you can be killed by traitors and my guess is that what I see is the red nickname I see and not other traitors, please correct this and I also noticed a flaw when you are thrown out, I see that I was not a traitor but the rest of the players see that I was a traitor and this is just a visual bug, I noticed when they wrote to me in the game that I created my own when I was already a ghost, and also add to the list the change of role werewolf, I hope I wrote it correctly and the translator didn’t screw up

**Comment by LilianPontes35** [comment]
action: RoleManager.Instance.SetRole(LocalPlayer, Role); 

This role is used in the PPM Change role. When a message is sent from the server with your role, this "action" is called and sets the characteristics of the role you have assigned, but this "action" does not send a message to the server, so for others, you are your original role.

**Comment by scp222thj** [comment]
Just as @LilianPontes35 pointed out, the ChangeRole cheat is client-side only, so it is basically a cheat only visible to you, but other players don't see it. There's currently no other way to change roles in the middle of a game without being banned by anticheat.
