### ISSUE TITLE
 Shape theater function

### ISSUE THREAD

**Issue by LongExplotion0** [scp222thj/MalumMenu#95]
I want a shape theater role in the change role. Currently, the function of shape theater cannot be utilized unless you become an imposter and become a shape theater.

As a cheat user, this is very necessary because you can be accused of using cheats by others.
do not force yourself. Even in its current state, it's amazing.

by japanese 
(translation)

![Among Us 2024_04_29 17_31_07](https://github.com/scp222thj/MalumMenu/assets/156439762/c0c29308-aa2c-447e-8269-61d4263e64f8)

**Comment by LilianPontes35** [comment]
**Shapeshifter role can only be used if it was already assigned at the start of the game
This is done to prevent the anticheat from kicking players**

**Comment by LongExplotion0** [comment]
I see 
thank you comment.
