### ISSUE TITLE
Add Code Extras For Guest Account In EOSManagerPatches 

### ISSUE THREAD

**Issue by LilianPontes35** [scp222thj/MalumMenu#96]
Remove the "and cannot include special characters/discriminator (#1234)" in the text config and put this code in EOSManagerPatches

[HarmonyPatch(typeof(EOSManager), nameof(EOSManager.UserIDToken), MethodType.Getter)]
public static class EOSManager_UserIDToken
{
    static string saveResult = string.Empty;
    public static bool Prefix(ref string __result)
    {
        if (saveResult != string.Empty)
        {
            __result = saveResult;
            return false;
        }
        return true;
    }
    public static void Postfix(ref string __result)
    {
	saveResult = __result;
    }
}

**Comment by scp222thj** [comment]
If you are interested in working on the code, please open a PR instead since issues are not really meant for that
